<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="wfrStudent.aspx.cs" Inherits="Student.wfrStudent" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:Label ID="lblErrorMsg" runat="server"></asp:Label>
            <div>
                <asp:Label ID="Label1" runat="server" Font-Bold="True" Font-Size="X-Large" Text="Danh sách sinh viên"></asp:Label>
                <br />
                <br />
            </div>
        </div>
        <asp:GridView ID="grvStudent" runat="server" AllowPaging="True" DataKeyNames="MaSV" Width="952px" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" OnPageIndexChanging="grvStudent_PageIndexChanging" PageSize="5" OnRowEditing="grvStudent_RowEditing" OnRowUpdating="grvStudent_RowUpdating" OnRowCancelingEdit="grvStudent_RowCancelingEdit" OnRowDeleting="grvStudent_RowDeleting" OnSelectedIndexChanging="grvStudent_SelectedIndexChanging" BackColor="White" BorderColor="#336666" BorderStyle="Double" BorderWidth="3px" CellPadding="4" GridLines="Horizontal">
            <Columns>
                <asp:BoundField DataField="MaSV" HeaderText="Mã Sinh Viên" ReadOnly="True" >
                <ItemStyle Width="150px" />
                </asp:BoundField>
                <asp:BoundField DataField="TenSV" HeaderText="Họ Tên" >
                <ItemStyle Width="200px" />
                </asp:BoundField>
                <asp:CheckBoxField DataField="Phai" HeaderText="Phái">
                <ItemStyle HorizontalAlign="Center" />
                </asp:CheckBoxField>
                <asp:BoundField DataField="Lop" HeaderText="Lớp">
                <ItemStyle HorizontalAlign="Center" />
                </asp:BoundField>
            </Columns>
            <FooterStyle BackColor="White" ForeColor="#333333" />
            <HeaderStyle BackColor="#336666" ForeColor="White" Font-Bold="True" />
            <PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="White" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#339966" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#487575" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#275353" />
        </asp:GridView>
    </form>
</body>
</html>
